### ISSUE TITLE
support generic Wikibase API authentication

### ISSUE THREAD

**Issue by christopher-johnson** [maxlath/wikidata-token#3]
I would like to use wikidata-agent on a non-Wikidata wikibase instance.   

I have changed the configuration in wikidata-token to point to this instance.  Even though wikidata-agent initializes successfully with the supplied credentials in the local.coffee, any POST fails with this error: 
`*******getToken*******
TypeError: Cannot read property 'join' of undefined
    at Object.module.exports.extractCookies (/home/christopher/IdeaProjects/wikidata-agent/node_modules/wikidata-token/build/utils.js:7:39)
`

I have noticed that wikidata.org somehow returns the Set-cookie header in a non-browser (curl) request eg. `curl https://wikidata.org -I` but for some reason my local MW installation does not, even though it is definitely set by PHP (as can be seen when using the debug toolbar).

I have tried force setting a cookie directly in the Apache conf, but it does not have the credentials needed by the API, so that does not work either.  

There must be some magic used in MW production that sets the cookie in the request header that I am not able to replicate.  Any ideas?

**Comment by christopher-johnson** [comment]
I have worked around this issue by commenting out line 17 of get_token_gettter.js:
`newCookies = _.extractCookies(res);`
It seems that it can get the first cookie (and token) from the request header, just not this final "new cookie".
Can you explain how this newCookies variable is intended to work?  It does not seem to matter if it is undefined for my use case.

**Comment by maxlath** [comment]
hello! sorry for the troubles, it was apparently not necessary to pass those additional cookies. I had quite a struggle figuring out which cookies where required, with which content-type etc, so I guess once it worked I didn't double check that everything was absolutely needed, sorry again!

So, now you can work with wikidata-agent against any Wikibase instance? :D
If so, could you make a PR on wikidata-agent to document the steps that need to be taken?
