### ISSUE TITLE
Update example

### ISSUE THREAD

**Issue by nichtich** [maxlath/wikidata-token#6]
The current example in README says "[used in wikidata-agent to create claims](https://github.com/maxlath/wikidata-agent/blob/master/server/lib/create_claim.coffee)" pointing to a removed file. I think the current example locations are:

* https://github.com/maxlath/wikidata-agent/blob/master/scripts/init_local_config.js#L40 for use with username and password
* https://github.com/maxlath/wikidata-edit/blob/master/lib/request.js#L14 also for use with OAuth

**Comment by maxlath** [comment]
yes, and wikidata-agent not being in active development anymore, I think linking to wikidata-edit alone would be better (103bfcb)
