### ISSUE TITLE
Explain need to use cookies

### ISSUE THREAD

**Issue by nichtich** [maxlath/wikidata-token#7]
It's not clear to me what the cookie is actually required for. MediaWiki API documentation only lists request parameter `token`, e.g. [wbsetclaim](https://www.wikidata.org/w/api.php?action=help&modules=wbsetclaim). Is it possible to create, edit, and delete Wikidata claims via MediaWiki API with tokens only or is the `cookie` value mandatory?

**Comment by maxlath** [comment]
When removing the cookies, I get the following error message:
```
{ error: 
      { code: 'badtoken',
        info: 'Invalid CSRF token.',
        '*': 'See https://www.wikidata.org/w/api.php for API usage. Subscribe to the mediawiki-api-announce mailing list at &lt;https://lists.wikimedia.org/mailman/listinfo/mediawiki-api-announce&gt; for notice of API deprecations and breaking changes.' },
     servedby: 'mw2135' } }
```

**Comment by nichtich** [comment]
Thanks for examination. I thought I could pass the cookie to another service to implement something similar to wikidata-agent but it turns out more complex, especially when I want OAuth.
